// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

#ifndef PROTOBUF_INCLUDED_planecontrol_2eproto
#define PROTOBUF_INCLUDED_planecontrol_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_planecontrol_2eproto 

namespace protobuf_planecontrol_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[7];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_planecontrol_2eproto
namespace tareados {
class InfoRequest;
class InfoRequestDefaultTypeInternal;
extern InfoRequestDefaultTypeInternal _InfoRequest_default_instance_;
class InfoResponse;
class InfoResponseDefaultTypeInternal;
extern InfoResponseDefaultTypeInternal _InfoResponse_default_instance_;
class LandRequest;
class LandRequestDefaultTypeInternal;
extern LandRequestDefaultTypeInternal _LandRequest_default_instance_;
class LandResponse;
class LandResponseDefaultTypeInternal;
extern LandResponseDefaultTypeInternal _LandResponse_default_instance_;
class TakeoffRequest;
class TakeoffRequestDefaultTypeInternal;
extern TakeoffRequestDefaultTypeInternal _TakeoffRequest_default_instance_;
class TakeoffResponse;
class TakeoffResponseDefaultTypeInternal;
extern TakeoffResponseDefaultTypeInternal _TakeoffResponse_default_instance_;
class plane;
class planeDefaultTypeInternal;
extern planeDefaultTypeInternal _plane_default_instance_;
}  // namespace tareados
namespace google {
namespace protobuf {
template<> ::tareados::InfoRequest* Arena::CreateMaybeMessage<::tareados::InfoRequest>(Arena*);
template<> ::tareados::InfoResponse* Arena::CreateMaybeMessage<::tareados::InfoResponse>(Arena*);
template<> ::tareados::LandRequest* Arena::CreateMaybeMessage<::tareados::LandRequest>(Arena*);
template<> ::tareados::LandResponse* Arena::CreateMaybeMessage<::tareados::LandResponse>(Arena*);
template<> ::tareados::TakeoffRequest* Arena::CreateMaybeMessage<::tareados::TakeoffRequest>(Arena*);
template<> ::tareados::TakeoffResponse* Arena::CreateMaybeMessage<::tareados::TakeoffResponse>(Arena*);
template<> ::tareados::plane* Arena::CreateMaybeMessage<::tareados::plane>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tareados {

// ===================================================================

class LandRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.LandRequest) */ {
 public:
  LandRequest();
  virtual ~LandRequest();

  LandRequest(const LandRequest& from);

  inline LandRequest& operator=(const LandRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LandRequest(LandRequest&& from) noexcept
    : LandRequest() {
    *this = ::std::move(from);
  }

  inline LandRequest& operator=(LandRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LandRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LandRequest* internal_default_instance() {
    return reinterpret_cast<const LandRequest*>(
               &_LandRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(LandRequest* other);
  friend void swap(LandRequest& a, LandRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LandRequest* New() const final {
    return CreateMaybeMessage<LandRequest>(NULL);
  }

  LandRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LandRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LandRequest& from);
  void MergeFrom(const LandRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LandRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 planeId = 1;
  void clear_planeid();
  static const int kPlaneIdFieldNumber = 1;
  ::google::protobuf::int32 planeid() const;
  void set_planeid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tareados.LandRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 planeid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class LandResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.LandResponse) */ {
 public:
  LandResponse();
  virtual ~LandResponse();

  LandResponse(const LandResponse& from);

  inline LandResponse& operator=(const LandResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LandResponse(LandResponse&& from) noexcept
    : LandResponse() {
    *this = ::std::move(from);
  }

  inline LandResponse& operator=(LandResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LandResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LandResponse* internal_default_instance() {
    return reinterpret_cast<const LandResponse*>(
               &_LandResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(LandResponse* other);
  friend void swap(LandResponse& a, LandResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LandResponse* New() const final {
    return CreateMaybeMessage<LandResponse>(NULL);
  }

  LandResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<LandResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const LandResponse& from);
  void MergeFrom(const LandResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LandResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 runway = 1;
  void clear_runway();
  static const int kRunwayFieldNumber = 1;
  ::google::protobuf::int32 runway() const;
  void set_runway(::google::protobuf::int32 value);

  // int32 queue = 2;
  void clear_queue();
  static const int kQueueFieldNumber = 2;
  ::google::protobuf::int32 queue() const;
  void set_queue(::google::protobuf::int32 value);

  // int32 altitude = 3;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 3;
  ::google::protobuf::int32 altitude() const;
  void set_altitude(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tareados.LandResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 runway_;
  ::google::protobuf::int32 queue_;
  ::google::protobuf::int32 altitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TakeoffRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.TakeoffRequest) */ {
 public:
  TakeoffRequest();
  virtual ~TakeoffRequest();

  TakeoffRequest(const TakeoffRequest& from);

  inline TakeoffRequest& operator=(const TakeoffRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TakeoffRequest(TakeoffRequest&& from) noexcept
    : TakeoffRequest() {
    *this = ::std::move(from);
  }

  inline TakeoffRequest& operator=(TakeoffRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TakeoffRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TakeoffRequest* internal_default_instance() {
    return reinterpret_cast<const TakeoffRequest*>(
               &_TakeoffRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(TakeoffRequest* other);
  friend void swap(TakeoffRequest& a, TakeoffRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TakeoffRequest* New() const final {
    return CreateMaybeMessage<TakeoffRequest>(NULL);
  }

  TakeoffRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TakeoffRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TakeoffRequest& from);
  void MergeFrom(const TakeoffRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TakeoffRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string dest = 2;
  void clear_dest();
  static const int kDestFieldNumber = 2;
  const ::std::string& dest() const;
  void set_dest(const ::std::string& value);
  #if LANG_CXX11
  void set_dest(::std::string&& value);
  #endif
  void set_dest(const char* value);
  void set_dest(const char* value, size_t size);
  ::std::string* mutable_dest();
  ::std::string* release_dest();
  void set_allocated_dest(::std::string* dest);

  // int32 planeId = 1;
  void clear_planeid();
  static const int kPlaneIdFieldNumber = 1;
  ::google::protobuf::int32 planeid() const;
  void set_planeid(::google::protobuf::int32 value);

  // int32 passengers = 3;
  void clear_passengers();
  static const int kPassengersFieldNumber = 3;
  ::google::protobuf::int32 passengers() const;
  void set_passengers(::google::protobuf::int32 value);

  // int32 fuel = 4;
  void clear_fuel();
  static const int kFuelFieldNumber = 4;
  ::google::protobuf::int32 fuel() const;
  void set_fuel(::google::protobuf::int32 value);

  // int32 maxLoad = 5;
  void clear_maxload();
  static const int kMaxLoadFieldNumber = 5;
  ::google::protobuf::int32 maxload() const;
  void set_maxload(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tareados.TakeoffRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr dest_;
  ::google::protobuf::int32 planeid_;
  ::google::protobuf::int32 passengers_;
  ::google::protobuf::int32 fuel_;
  ::google::protobuf::int32 maxload_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TakeoffResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.TakeoffResponse) */ {
 public:
  TakeoffResponse();
  virtual ~TakeoffResponse();

  TakeoffResponse(const TakeoffResponse& from);

  inline TakeoffResponse& operator=(const TakeoffResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TakeoffResponse(TakeoffResponse&& from) noexcept
    : TakeoffResponse() {
    *this = ::std::move(from);
  }

  inline TakeoffResponse& operator=(TakeoffResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TakeoffResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TakeoffResponse* internal_default_instance() {
    return reinterpret_cast<const TakeoffResponse*>(
               &_TakeoffResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(TakeoffResponse* other);
  friend void swap(TakeoffResponse& a, TakeoffResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TakeoffResponse* New() const final {
    return CreateMaybeMessage<TakeoffResponse>(NULL);
  }

  TakeoffResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TakeoffResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TakeoffResponse& from);
  void MergeFrom(const TakeoffResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TakeoffResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes ipDest = 3;
  void clear_ipdest();
  static const int kIpDestFieldNumber = 3;
  const ::std::string& ipdest() const;
  void set_ipdest(const ::std::string& value);
  #if LANG_CXX11
  void set_ipdest(::std::string&& value);
  #endif
  void set_ipdest(const char* value);
  void set_ipdest(const void* value, size_t size);
  ::std::string* mutable_ipdest();
  ::std::string* release_ipdest();
  void set_allocated_ipdest(::std::string* ipdest);

  // bytes portDest = 4;
  void clear_portdest();
  static const int kPortDestFieldNumber = 4;
  const ::std::string& portdest() const;
  void set_portdest(const ::std::string& value);
  #if LANG_CXX11
  void set_portdest(::std::string&& value);
  #endif
  void set_portdest(const char* value);
  void set_portdest(const void* value, size_t size);
  ::std::string* mutable_portdest();
  ::std::string* release_portdest();
  void set_allocated_portdest(::std::string* portdest);

  // string prevPlane = 6;
  void clear_prevplane();
  static const int kPrevPlaneFieldNumber = 6;
  const ::std::string& prevplane() const;
  void set_prevplane(const ::std::string& value);
  #if LANG_CXX11
  void set_prevplane(::std::string&& value);
  #endif
  void set_prevplane(const char* value);
  void set_prevplane(const char* value, size_t size);
  ::std::string* mutable_prevplane();
  ::std::string* release_prevplane();
  void set_allocated_prevplane(::std::string* prevplane);

  // int32 altitude = 1;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 1;
  ::google::protobuf::int32 altitude() const;
  void set_altitude(::google::protobuf::int32 value);

  // int32 runway = 2;
  void clear_runway();
  static const int kRunwayFieldNumber = 2;
  ::google::protobuf::int32 runway() const;
  void set_runway(::google::protobuf::int32 value);

  // int32 queuePos = 5;
  void clear_queuepos();
  static const int kQueuePosFieldNumber = 5;
  ::google::protobuf::int32 queuepos() const;
  void set_queuepos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tareados.TakeoffResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr ipdest_;
  ::google::protobuf::internal::ArenaStringPtr portdest_;
  ::google::protobuf::internal::ArenaStringPtr prevplane_;
  ::google::protobuf::int32 altitude_;
  ::google::protobuf::int32 runway_;
  ::google::protobuf::int32 queuepos_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InfoRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.InfoRequest) */ {
 public:
  InfoRequest();
  virtual ~InfoRequest();

  InfoRequest(const InfoRequest& from);

  inline InfoRequest& operator=(const InfoRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InfoRequest(InfoRequest&& from) noexcept
    : InfoRequest() {
    *this = ::std::move(from);
  }

  inline InfoRequest& operator=(InfoRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InfoRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InfoRequest* internal_default_instance() {
    return reinterpret_cast<const InfoRequest*>(
               &_InfoRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(InfoRequest* other);
  friend void swap(InfoRequest& a, InfoRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InfoRequest* New() const final {
    return CreateMaybeMessage<InfoRequest>(NULL);
  }

  InfoRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InfoRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InfoRequest& from);
  void MergeFrom(const InfoRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InfoRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string controlTower = 1;
  void clear_controltower();
  static const int kControlTowerFieldNumber = 1;
  const ::std::string& controltower() const;
  void set_controltower(const ::std::string& value);
  #if LANG_CXX11
  void set_controltower(::std::string&& value);
  #endif
  void set_controltower(const char* value);
  void set_controltower(const char* value, size_t size);
  ::std::string* mutable_controltower();
  ::std::string* release_controltower();
  void set_allocated_controltower(::std::string* controltower);

  // @@protoc_insertion_point(class_scope:tareados.InfoRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr controltower_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class InfoResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.InfoResponse) */ {
 public:
  InfoResponse();
  virtual ~InfoResponse();

  InfoResponse(const InfoResponse& from);

  inline InfoResponse& operator=(const InfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  InfoResponse(InfoResponse&& from) noexcept
    : InfoResponse() {
    *this = ::std::move(from);
  }

  inline InfoResponse& operator=(InfoResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const InfoResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const InfoResponse* internal_default_instance() {
    return reinterpret_cast<const InfoResponse*>(
               &_InfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(InfoResponse* other);
  friend void swap(InfoResponse& a, InfoResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline InfoResponse* New() const final {
    return CreateMaybeMessage<InfoResponse>(NULL);
  }

  InfoResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<InfoResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const InfoResponse& from);
  void MergeFrom(const InfoResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InfoResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tareados.plane departurePlane = 1;
  int departureplane_size() const;
  void clear_departureplane();
  static const int kDeparturePlaneFieldNumber = 1;
  ::tareados::plane* mutable_departureplane(int index);
  ::google::protobuf::RepeatedPtrField< ::tareados::plane >*
      mutable_departureplane();
  const ::tareados::plane& departureplane(int index) const;
  ::tareados::plane* add_departureplane();
  const ::google::protobuf::RepeatedPtrField< ::tareados::plane >&
      departureplane() const;

  // repeated .tareados.plane arrivalPlane = 2;
  int arrivalplane_size() const;
  void clear_arrivalplane();
  static const int kArrivalPlaneFieldNumber = 2;
  ::tareados::plane* mutable_arrivalplane(int index);
  ::google::protobuf::RepeatedPtrField< ::tareados::plane >*
      mutable_arrivalplane();
  const ::tareados::plane& arrivalplane(int index) const;
  ::tareados::plane* add_arrivalplane();
  const ::google::protobuf::RepeatedPtrField< ::tareados::plane >&
      arrivalplane() const;

  // @@protoc_insertion_point(class_scope:tareados.InfoResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tareados::plane > departureplane_;
  ::google::protobuf::RepeatedPtrField< ::tareados::plane > arrivalplane_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class plane : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tareados.plane) */ {
 public:
  plane();
  virtual ~plane();

  plane(const plane& from);

  inline plane& operator=(const plane& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  plane(plane&& from) noexcept
    : plane() {
    *this = ::std::move(from);
  }

  inline plane& operator=(plane&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const plane& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const plane* internal_default_instance() {
    return reinterpret_cast<const plane*>(
               &_plane_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(plane* other);
  friend void swap(plane& a, plane& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline plane* New() const final {
    return CreateMaybeMessage<plane>(NULL);
  }

  plane* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<plane>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const plane& from);
  void MergeFrom(const plane& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(plane* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string sourceName = 2;
  void clear_sourcename();
  static const int kSourceNameFieldNumber = 2;
  const ::std::string& sourcename() const;
  void set_sourcename(const ::std::string& value);
  #if LANG_CXX11
  void set_sourcename(::std::string&& value);
  #endif
  void set_sourcename(const char* value);
  void set_sourcename(const char* value, size_t size);
  ::std::string* mutable_sourcename();
  ::std::string* release_sourcename();
  void set_allocated_sourcename(::std::string* sourcename);

  // string destName = 3;
  void clear_destname();
  static const int kDestNameFieldNumber = 3;
  const ::std::string& destname() const;
  void set_destname(const ::std::string& value);
  #if LANG_CXX11
  void set_destname(::std::string&& value);
  #endif
  void set_destname(const char* value);
  void set_destname(const char* value, size_t size);
  ::std::string* mutable_destname();
  ::std::string* release_destname();
  void set_allocated_destname(::std::string* destname);

  // string departureTime = 4;
  void clear_departuretime();
  static const int kDepartureTimeFieldNumber = 4;
  const ::std::string& departuretime() const;
  void set_departuretime(const ::std::string& value);
  #if LANG_CXX11
  void set_departuretime(::std::string&& value);
  #endif
  void set_departuretime(const char* value);
  void set_departuretime(const char* value, size_t size);
  ::std::string* mutable_departuretime();
  ::std::string* release_departuretime();
  void set_allocated_departuretime(::std::string* departuretime);

  // string arrivalTime = 5;
  void clear_arrivaltime();
  static const int kArrivalTimeFieldNumber = 5;
  const ::std::string& arrivaltime() const;
  void set_arrivaltime(const ::std::string& value);
  #if LANG_CXX11
  void set_arrivaltime(::std::string&& value);
  #endif
  void set_arrivaltime(const char* value);
  void set_arrivaltime(const char* value, size_t size);
  ::std::string* mutable_arrivaltime();
  ::std::string* release_arrivaltime();
  void set_allocated_arrivaltime(::std::string* arrivaltime);

  // int32 planeId = 1;
  void clear_planeid();
  static const int kPlaneIdFieldNumber = 1;
  ::google::protobuf::int32 planeid() const;
  void set_planeid(::google::protobuf::int32 value);

  // int32 sourceRunway = 6;
  void clear_sourcerunway();
  static const int kSourceRunwayFieldNumber = 6;
  ::google::protobuf::int32 sourcerunway() const;
  void set_sourcerunway(::google::protobuf::int32 value);

  // int32 destRunway = 7;
  void clear_destrunway();
  static const int kDestRunwayFieldNumber = 7;
  ::google::protobuf::int32 destrunway() const;
  void set_destrunway(::google::protobuf::int32 value);

  // int32 altitude = 8;
  void clear_altitude();
  static const int kAltitudeFieldNumber = 8;
  ::google::protobuf::int32 altitude() const;
  void set_altitude(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tareados.plane)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr sourcename_;
  ::google::protobuf::internal::ArenaStringPtr destname_;
  ::google::protobuf::internal::ArenaStringPtr departuretime_;
  ::google::protobuf::internal::ArenaStringPtr arrivaltime_;
  ::google::protobuf::int32 planeid_;
  ::google::protobuf::int32 sourcerunway_;
  ::google::protobuf::int32 destrunway_;
  ::google::protobuf::int32 altitude_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_planecontrol_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LandRequest

// int32 planeId = 1;
inline void LandRequest::clear_planeid() {
  planeid_ = 0;
}
inline ::google::protobuf::int32 LandRequest::planeid() const {
  // @@protoc_insertion_point(field_get:tareados.LandRequest.planeId)
  return planeid_;
}
inline void LandRequest::set_planeid(::google::protobuf::int32 value) {
  
  planeid_ = value;
  // @@protoc_insertion_point(field_set:tareados.LandRequest.planeId)
}

// -------------------------------------------------------------------

// LandResponse

// int32 runway = 1;
inline void LandResponse::clear_runway() {
  runway_ = 0;
}
inline ::google::protobuf::int32 LandResponse::runway() const {
  // @@protoc_insertion_point(field_get:tareados.LandResponse.runway)
  return runway_;
}
inline void LandResponse::set_runway(::google::protobuf::int32 value) {
  
  runway_ = value;
  // @@protoc_insertion_point(field_set:tareados.LandResponse.runway)
}

// int32 queue = 2;
inline void LandResponse::clear_queue() {
  queue_ = 0;
}
inline ::google::protobuf::int32 LandResponse::queue() const {
  // @@protoc_insertion_point(field_get:tareados.LandResponse.queue)
  return queue_;
}
inline void LandResponse::set_queue(::google::protobuf::int32 value) {
  
  queue_ = value;
  // @@protoc_insertion_point(field_set:tareados.LandResponse.queue)
}

// int32 altitude = 3;
inline void LandResponse::clear_altitude() {
  altitude_ = 0;
}
inline ::google::protobuf::int32 LandResponse::altitude() const {
  // @@protoc_insertion_point(field_get:tareados.LandResponse.altitude)
  return altitude_;
}
inline void LandResponse::set_altitude(::google::protobuf::int32 value) {
  
  altitude_ = value;
  // @@protoc_insertion_point(field_set:tareados.LandResponse.altitude)
}

// -------------------------------------------------------------------

// TakeoffRequest

// int32 planeId = 1;
inline void TakeoffRequest::clear_planeid() {
  planeid_ = 0;
}
inline ::google::protobuf::int32 TakeoffRequest::planeid() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffRequest.planeId)
  return planeid_;
}
inline void TakeoffRequest::set_planeid(::google::protobuf::int32 value) {
  
  planeid_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffRequest.planeId)
}

// string dest = 2;
inline void TakeoffRequest::clear_dest() {
  dest_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TakeoffRequest::dest() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffRequest.dest)
  return dest_.GetNoArena();
}
inline void TakeoffRequest::set_dest(const ::std::string& value) {
  
  dest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.TakeoffRequest.dest)
}
#if LANG_CXX11
inline void TakeoffRequest::set_dest(::std::string&& value) {
  
  dest_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.TakeoffRequest.dest)
}
#endif
inline void TakeoffRequest::set_dest(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  dest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.TakeoffRequest.dest)
}
inline void TakeoffRequest::set_dest(const char* value, size_t size) {
  
  dest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.TakeoffRequest.dest)
}
inline ::std::string* TakeoffRequest::mutable_dest() {
  
  // @@protoc_insertion_point(field_mutable:tareados.TakeoffRequest.dest)
  return dest_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TakeoffRequest::release_dest() {
  // @@protoc_insertion_point(field_release:tareados.TakeoffRequest.dest)
  
  return dest_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TakeoffRequest::set_allocated_dest(::std::string* dest) {
  if (dest != NULL) {
    
  } else {
    
  }
  dest_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dest);
  // @@protoc_insertion_point(field_set_allocated:tareados.TakeoffRequest.dest)
}

// int32 passengers = 3;
inline void TakeoffRequest::clear_passengers() {
  passengers_ = 0;
}
inline ::google::protobuf::int32 TakeoffRequest::passengers() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffRequest.passengers)
  return passengers_;
}
inline void TakeoffRequest::set_passengers(::google::protobuf::int32 value) {
  
  passengers_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffRequest.passengers)
}

// int32 fuel = 4;
inline void TakeoffRequest::clear_fuel() {
  fuel_ = 0;
}
inline ::google::protobuf::int32 TakeoffRequest::fuel() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffRequest.fuel)
  return fuel_;
}
inline void TakeoffRequest::set_fuel(::google::protobuf::int32 value) {
  
  fuel_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffRequest.fuel)
}

// int32 maxLoad = 5;
inline void TakeoffRequest::clear_maxload() {
  maxload_ = 0;
}
inline ::google::protobuf::int32 TakeoffRequest::maxload() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffRequest.maxLoad)
  return maxload_;
}
inline void TakeoffRequest::set_maxload(::google::protobuf::int32 value) {
  
  maxload_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffRequest.maxLoad)
}

// -------------------------------------------------------------------

// TakeoffResponse

// int32 altitude = 1;
inline void TakeoffResponse::clear_altitude() {
  altitude_ = 0;
}
inline ::google::protobuf::int32 TakeoffResponse::altitude() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.altitude)
  return altitude_;
}
inline void TakeoffResponse::set_altitude(::google::protobuf::int32 value) {
  
  altitude_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.altitude)
}

// int32 runway = 2;
inline void TakeoffResponse::clear_runway() {
  runway_ = 0;
}
inline ::google::protobuf::int32 TakeoffResponse::runway() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.runway)
  return runway_;
}
inline void TakeoffResponse::set_runway(::google::protobuf::int32 value) {
  
  runway_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.runway)
}

// bytes ipDest = 3;
inline void TakeoffResponse::clear_ipdest() {
  ipdest_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TakeoffResponse::ipdest() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.ipDest)
  return ipdest_.GetNoArena();
}
inline void TakeoffResponse::set_ipdest(const ::std::string& value) {
  
  ipdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.ipDest)
}
#if LANG_CXX11
inline void TakeoffResponse::set_ipdest(::std::string&& value) {
  
  ipdest_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.TakeoffResponse.ipDest)
}
#endif
inline void TakeoffResponse::set_ipdest(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ipdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.TakeoffResponse.ipDest)
}
inline void TakeoffResponse::set_ipdest(const void* value, size_t size) {
  
  ipdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.TakeoffResponse.ipDest)
}
inline ::std::string* TakeoffResponse::mutable_ipdest() {
  
  // @@protoc_insertion_point(field_mutable:tareados.TakeoffResponse.ipDest)
  return ipdest_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TakeoffResponse::release_ipdest() {
  // @@protoc_insertion_point(field_release:tareados.TakeoffResponse.ipDest)
  
  return ipdest_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TakeoffResponse::set_allocated_ipdest(::std::string* ipdest) {
  if (ipdest != NULL) {
    
  } else {
    
  }
  ipdest_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ipdest);
  // @@protoc_insertion_point(field_set_allocated:tareados.TakeoffResponse.ipDest)
}

// bytes portDest = 4;
inline void TakeoffResponse::clear_portdest() {
  portdest_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TakeoffResponse::portdest() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.portDest)
  return portdest_.GetNoArena();
}
inline void TakeoffResponse::set_portdest(const ::std::string& value) {
  
  portdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.portDest)
}
#if LANG_CXX11
inline void TakeoffResponse::set_portdest(::std::string&& value) {
  
  portdest_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.TakeoffResponse.portDest)
}
#endif
inline void TakeoffResponse::set_portdest(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  portdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.TakeoffResponse.portDest)
}
inline void TakeoffResponse::set_portdest(const void* value, size_t size) {
  
  portdest_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.TakeoffResponse.portDest)
}
inline ::std::string* TakeoffResponse::mutable_portdest() {
  
  // @@protoc_insertion_point(field_mutable:tareados.TakeoffResponse.portDest)
  return portdest_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TakeoffResponse::release_portdest() {
  // @@protoc_insertion_point(field_release:tareados.TakeoffResponse.portDest)
  
  return portdest_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TakeoffResponse::set_allocated_portdest(::std::string* portdest) {
  if (portdest != NULL) {
    
  } else {
    
  }
  portdest_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), portdest);
  // @@protoc_insertion_point(field_set_allocated:tareados.TakeoffResponse.portDest)
}

// int32 queuePos = 5;
inline void TakeoffResponse::clear_queuepos() {
  queuepos_ = 0;
}
inline ::google::protobuf::int32 TakeoffResponse::queuepos() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.queuePos)
  return queuepos_;
}
inline void TakeoffResponse::set_queuepos(::google::protobuf::int32 value) {
  
  queuepos_ = value;
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.queuePos)
}

// string prevPlane = 6;
inline void TakeoffResponse::clear_prevplane() {
  prevplane_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TakeoffResponse::prevplane() const {
  // @@protoc_insertion_point(field_get:tareados.TakeoffResponse.prevPlane)
  return prevplane_.GetNoArena();
}
inline void TakeoffResponse::set_prevplane(const ::std::string& value) {
  
  prevplane_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.TakeoffResponse.prevPlane)
}
#if LANG_CXX11
inline void TakeoffResponse::set_prevplane(::std::string&& value) {
  
  prevplane_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.TakeoffResponse.prevPlane)
}
#endif
inline void TakeoffResponse::set_prevplane(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  prevplane_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.TakeoffResponse.prevPlane)
}
inline void TakeoffResponse::set_prevplane(const char* value, size_t size) {
  
  prevplane_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.TakeoffResponse.prevPlane)
}
inline ::std::string* TakeoffResponse::mutable_prevplane() {
  
  // @@protoc_insertion_point(field_mutable:tareados.TakeoffResponse.prevPlane)
  return prevplane_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TakeoffResponse::release_prevplane() {
  // @@protoc_insertion_point(field_release:tareados.TakeoffResponse.prevPlane)
  
  return prevplane_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TakeoffResponse::set_allocated_prevplane(::std::string* prevplane) {
  if (prevplane != NULL) {
    
  } else {
    
  }
  prevplane_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), prevplane);
  // @@protoc_insertion_point(field_set_allocated:tareados.TakeoffResponse.prevPlane)
}

// -------------------------------------------------------------------

// InfoRequest

// string controlTower = 1;
inline void InfoRequest::clear_controltower() {
  controltower_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& InfoRequest::controltower() const {
  // @@protoc_insertion_point(field_get:tareados.InfoRequest.controlTower)
  return controltower_.GetNoArena();
}
inline void InfoRequest::set_controltower(const ::std::string& value) {
  
  controltower_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.InfoRequest.controlTower)
}
#if LANG_CXX11
inline void InfoRequest::set_controltower(::std::string&& value) {
  
  controltower_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.InfoRequest.controlTower)
}
#endif
inline void InfoRequest::set_controltower(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  controltower_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.InfoRequest.controlTower)
}
inline void InfoRequest::set_controltower(const char* value, size_t size) {
  
  controltower_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.InfoRequest.controlTower)
}
inline ::std::string* InfoRequest::mutable_controltower() {
  
  // @@protoc_insertion_point(field_mutable:tareados.InfoRequest.controlTower)
  return controltower_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* InfoRequest::release_controltower() {
  // @@protoc_insertion_point(field_release:tareados.InfoRequest.controlTower)
  
  return controltower_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void InfoRequest::set_allocated_controltower(::std::string* controltower) {
  if (controltower != NULL) {
    
  } else {
    
  }
  controltower_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), controltower);
  // @@protoc_insertion_point(field_set_allocated:tareados.InfoRequest.controlTower)
}

// -------------------------------------------------------------------

// InfoResponse

// repeated .tareados.plane departurePlane = 1;
inline int InfoResponse::departureplane_size() const {
  return departureplane_.size();
}
inline void InfoResponse::clear_departureplane() {
  departureplane_.Clear();
}
inline ::tareados::plane* InfoResponse::mutable_departureplane(int index) {
  // @@protoc_insertion_point(field_mutable:tareados.InfoResponse.departurePlane)
  return departureplane_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tareados::plane >*
InfoResponse::mutable_departureplane() {
  // @@protoc_insertion_point(field_mutable_list:tareados.InfoResponse.departurePlane)
  return &departureplane_;
}
inline const ::tareados::plane& InfoResponse::departureplane(int index) const {
  // @@protoc_insertion_point(field_get:tareados.InfoResponse.departurePlane)
  return departureplane_.Get(index);
}
inline ::tareados::plane* InfoResponse::add_departureplane() {
  // @@protoc_insertion_point(field_add:tareados.InfoResponse.departurePlane)
  return departureplane_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tareados::plane >&
InfoResponse::departureplane() const {
  // @@protoc_insertion_point(field_list:tareados.InfoResponse.departurePlane)
  return departureplane_;
}

// repeated .tareados.plane arrivalPlane = 2;
inline int InfoResponse::arrivalplane_size() const {
  return arrivalplane_.size();
}
inline void InfoResponse::clear_arrivalplane() {
  arrivalplane_.Clear();
}
inline ::tareados::plane* InfoResponse::mutable_arrivalplane(int index) {
  // @@protoc_insertion_point(field_mutable:tareados.InfoResponse.arrivalPlane)
  return arrivalplane_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tareados::plane >*
InfoResponse::mutable_arrivalplane() {
  // @@protoc_insertion_point(field_mutable_list:tareados.InfoResponse.arrivalPlane)
  return &arrivalplane_;
}
inline const ::tareados::plane& InfoResponse::arrivalplane(int index) const {
  // @@protoc_insertion_point(field_get:tareados.InfoResponse.arrivalPlane)
  return arrivalplane_.Get(index);
}
inline ::tareados::plane* InfoResponse::add_arrivalplane() {
  // @@protoc_insertion_point(field_add:tareados.InfoResponse.arrivalPlane)
  return arrivalplane_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tareados::plane >&
InfoResponse::arrivalplane() const {
  // @@protoc_insertion_point(field_list:tareados.InfoResponse.arrivalPlane)
  return arrivalplane_;
}

// -------------------------------------------------------------------

// plane

// int32 planeId = 1;
inline void plane::clear_planeid() {
  planeid_ = 0;
}
inline ::google::protobuf::int32 plane::planeid() const {
  // @@protoc_insertion_point(field_get:tareados.plane.planeId)
  return planeid_;
}
inline void plane::set_planeid(::google::protobuf::int32 value) {
  
  planeid_ = value;
  // @@protoc_insertion_point(field_set:tareados.plane.planeId)
}

// string sourceName = 2;
inline void plane::clear_sourcename() {
  sourcename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& plane::sourcename() const {
  // @@protoc_insertion_point(field_get:tareados.plane.sourceName)
  return sourcename_.GetNoArena();
}
inline void plane::set_sourcename(const ::std::string& value) {
  
  sourcename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.plane.sourceName)
}
#if LANG_CXX11
inline void plane::set_sourcename(::std::string&& value) {
  
  sourcename_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.plane.sourceName)
}
#endif
inline void plane::set_sourcename(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  sourcename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.plane.sourceName)
}
inline void plane::set_sourcename(const char* value, size_t size) {
  
  sourcename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.plane.sourceName)
}
inline ::std::string* plane::mutable_sourcename() {
  
  // @@protoc_insertion_point(field_mutable:tareados.plane.sourceName)
  return sourcename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* plane::release_sourcename() {
  // @@protoc_insertion_point(field_release:tareados.plane.sourceName)
  
  return sourcename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void plane::set_allocated_sourcename(::std::string* sourcename) {
  if (sourcename != NULL) {
    
  } else {
    
  }
  sourcename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sourcename);
  // @@protoc_insertion_point(field_set_allocated:tareados.plane.sourceName)
}

// string destName = 3;
inline void plane::clear_destname() {
  destname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& plane::destname() const {
  // @@protoc_insertion_point(field_get:tareados.plane.destName)
  return destname_.GetNoArena();
}
inline void plane::set_destname(const ::std::string& value) {
  
  destname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.plane.destName)
}
#if LANG_CXX11
inline void plane::set_destname(::std::string&& value) {
  
  destname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.plane.destName)
}
#endif
inline void plane::set_destname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  destname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.plane.destName)
}
inline void plane::set_destname(const char* value, size_t size) {
  
  destname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.plane.destName)
}
inline ::std::string* plane::mutable_destname() {
  
  // @@protoc_insertion_point(field_mutable:tareados.plane.destName)
  return destname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* plane::release_destname() {
  // @@protoc_insertion_point(field_release:tareados.plane.destName)
  
  return destname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void plane::set_allocated_destname(::std::string* destname) {
  if (destname != NULL) {
    
  } else {
    
  }
  destname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destname);
  // @@protoc_insertion_point(field_set_allocated:tareados.plane.destName)
}

// string departureTime = 4;
inline void plane::clear_departuretime() {
  departuretime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& plane::departuretime() const {
  // @@protoc_insertion_point(field_get:tareados.plane.departureTime)
  return departuretime_.GetNoArena();
}
inline void plane::set_departuretime(const ::std::string& value) {
  
  departuretime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.plane.departureTime)
}
#if LANG_CXX11
inline void plane::set_departuretime(::std::string&& value) {
  
  departuretime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.plane.departureTime)
}
#endif
inline void plane::set_departuretime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  departuretime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.plane.departureTime)
}
inline void plane::set_departuretime(const char* value, size_t size) {
  
  departuretime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.plane.departureTime)
}
inline ::std::string* plane::mutable_departuretime() {
  
  // @@protoc_insertion_point(field_mutable:tareados.plane.departureTime)
  return departuretime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* plane::release_departuretime() {
  // @@protoc_insertion_point(field_release:tareados.plane.departureTime)
  
  return departuretime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void plane::set_allocated_departuretime(::std::string* departuretime) {
  if (departuretime != NULL) {
    
  } else {
    
  }
  departuretime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), departuretime);
  // @@protoc_insertion_point(field_set_allocated:tareados.plane.departureTime)
}

// string arrivalTime = 5;
inline void plane::clear_arrivaltime() {
  arrivaltime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& plane::arrivaltime() const {
  // @@protoc_insertion_point(field_get:tareados.plane.arrivalTime)
  return arrivaltime_.GetNoArena();
}
inline void plane::set_arrivaltime(const ::std::string& value) {
  
  arrivaltime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tareados.plane.arrivalTime)
}
#if LANG_CXX11
inline void plane::set_arrivaltime(::std::string&& value) {
  
  arrivaltime_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tareados.plane.arrivalTime)
}
#endif
inline void plane::set_arrivaltime(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  arrivaltime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tareados.plane.arrivalTime)
}
inline void plane::set_arrivaltime(const char* value, size_t size) {
  
  arrivaltime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tareados.plane.arrivalTime)
}
inline ::std::string* plane::mutable_arrivaltime() {
  
  // @@protoc_insertion_point(field_mutable:tareados.plane.arrivalTime)
  return arrivaltime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* plane::release_arrivaltime() {
  // @@protoc_insertion_point(field_release:tareados.plane.arrivalTime)
  
  return arrivaltime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void plane::set_allocated_arrivaltime(::std::string* arrivaltime) {
  if (arrivaltime != NULL) {
    
  } else {
    
  }
  arrivaltime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arrivaltime);
  // @@protoc_insertion_point(field_set_allocated:tareados.plane.arrivalTime)
}

// int32 sourceRunway = 6;
inline void plane::clear_sourcerunway() {
  sourcerunway_ = 0;
}
inline ::google::protobuf::int32 plane::sourcerunway() const {
  // @@protoc_insertion_point(field_get:tareados.plane.sourceRunway)
  return sourcerunway_;
}
inline void plane::set_sourcerunway(::google::protobuf::int32 value) {
  
  sourcerunway_ = value;
  // @@protoc_insertion_point(field_set:tareados.plane.sourceRunway)
}

// int32 destRunway = 7;
inline void plane::clear_destrunway() {
  destrunway_ = 0;
}
inline ::google::protobuf::int32 plane::destrunway() const {
  // @@protoc_insertion_point(field_get:tareados.plane.destRunway)
  return destrunway_;
}
inline void plane::set_destrunway(::google::protobuf::int32 value) {
  
  destrunway_ = value;
  // @@protoc_insertion_point(field_set:tareados.plane.destRunway)
}

// int32 altitude = 8;
inline void plane::clear_altitude() {
  altitude_ = 0;
}
inline ::google::protobuf::int32 plane::altitude() const {
  // @@protoc_insertion_point(field_get:tareados.plane.altitude)
  return altitude_;
}
inline void plane::set_altitude(::google::protobuf::int32 value) {
  
  altitude_ = value;
  // @@protoc_insertion_point(field_set:tareados.plane.altitude)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tareados

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_planecontrol_2eproto
