// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

public interface LandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.LandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 runway = 1;</code>
   */
  int getRunway();

  /**
   * <code>int32 queue = 2;</code>
   */
  int getQueue();

  /**
   * <code>int32 altitude = 3;</code>
   */
  int getAltitude();

  /**
   * <code>string destName = 4;</code>
   */
  java.lang.String getDestName();
  /**
   * <code>string destName = 4;</code>
   */
  com.google.protobuf.ByteString
      getDestNameBytes();
}
