// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

public interface TakeoffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.TakeoffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  boolean hasPlane();
  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  avion.proto.PlaneMsge getPlane();
  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  avion.proto.PlaneMsgeOrBuilder getPlaneOrBuilder();

  /**
   * <code>string dest = 2;</code>
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <pre>
   *si el avión necesita instrucciones = true sino no
   * </pre>
   *
   * <code>bool instOK = 3;</code>
   */
  boolean getInstOK();

  /**
   * <pre>
   *si el avion esta listo para despegar (presionar enter)
   * </pre>
   *
   * <code>bool flyOK = 4;</code>
   */
  boolean getFlyOK();
}
