// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

public interface InfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.InfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id de torre de control
   * </pre>
   *
   * <code>string control_tower = 1;</code>
   */
  java.lang.String getControlTower();
  /**
   * <pre>
   *id de torre de control
   * </pre>
   *
   * <code>string control_tower = 1;</code>
   */
  com.google.protobuf.ByteString
      getControlTowerBytes();
}
