// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

/**
 * Protobuf type {@code tareados.InfoResponse}
 */
public  final class InfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tareados.InfoResponse)
    InfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InfoResponse.newBuilder() to construct.
  private InfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InfoResponse() {
    departurePlane_ = java.util.Collections.emptyList();
    arrivalPlane_ = java.util.Collections.emptyList();
    controlTower_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              departurePlane_ = new java.util.ArrayList<avion.proto.PlaneMsge>();
              mutable_bitField0_ |= 0x00000001;
            }
            departurePlane_.add(
                input.readMessage(avion.proto.PlaneMsge.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              arrivalPlane_ = new java.util.ArrayList<avion.proto.PlaneMsge>();
              mutable_bitField0_ |= 0x00000002;
            }
            arrivalPlane_.add(
                input.readMessage(avion.proto.PlaneMsge.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            controlTower_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        departurePlane_ = java.util.Collections.unmodifiableList(departurePlane_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        arrivalPlane_ = java.util.Collections.unmodifiableList(arrivalPlane_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_InfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_InfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            avion.proto.InfoResponse.class, avion.proto.InfoResponse.Builder.class);
  }

  private int bitField0_;
  public static final int DEPARTUREPLANE_FIELD_NUMBER = 1;
  private java.util.List<avion.proto.PlaneMsge> departurePlane_;
  /**
   * <pre>
   *id de vuelo de salida desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
   */
  public java.util.List<avion.proto.PlaneMsge> getDeparturePlaneList() {
    return departurePlane_;
  }
  /**
   * <pre>
   *id de vuelo de salida desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
   */
  public java.util.List<? extends avion.proto.PlaneMsgeOrBuilder> 
      getDeparturePlaneOrBuilderList() {
    return departurePlane_;
  }
  /**
   * <pre>
   *id de vuelo de salida desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
   */
  public int getDeparturePlaneCount() {
    return departurePlane_.size();
  }
  /**
   * <pre>
   *id de vuelo de salida desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
   */
  public avion.proto.PlaneMsge getDeparturePlane(int index) {
    return departurePlane_.get(index);
  }
  /**
   * <pre>
   *id de vuelo de salida desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
   */
  public avion.proto.PlaneMsgeOrBuilder getDeparturePlaneOrBuilder(
      int index) {
    return departurePlane_.get(index);
  }

  public static final int ARRIVALPLANE_FIELD_NUMBER = 2;
  private java.util.List<avion.proto.PlaneMsge> arrivalPlane_;
  /**
   * <pre>
   *id de vuelo de entrada desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
   */
  public java.util.List<avion.proto.PlaneMsge> getArrivalPlaneList() {
    return arrivalPlane_;
  }
  /**
   * <pre>
   *id de vuelo de entrada desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
   */
  public java.util.List<? extends avion.proto.PlaneMsgeOrBuilder> 
      getArrivalPlaneOrBuilderList() {
    return arrivalPlane_;
  }
  /**
   * <pre>
   *id de vuelo de entrada desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
   */
  public int getArrivalPlaneCount() {
    return arrivalPlane_.size();
  }
  /**
   * <pre>
   *id de vuelo de entrada desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
   */
  public avion.proto.PlaneMsge getArrivalPlane(int index) {
    return arrivalPlane_.get(index);
  }
  /**
   * <pre>
   *id de vuelo de entrada desde el aeropuerto
   * </pre>
   *
   * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
   */
  public avion.proto.PlaneMsgeOrBuilder getArrivalPlaneOrBuilder(
      int index) {
    return arrivalPlane_.get(index);
  }

  public static final int CONTROL_TOWER_FIELD_NUMBER = 3;
  private volatile java.lang.Object controlTower_;
  /**
   * <pre>
   *nombre de la torre de control
   * </pre>
   *
   * <code>string control_tower = 3;</code>
   */
  public java.lang.String getControlTower() {
    java.lang.Object ref = controlTower_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      controlTower_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *nombre de la torre de control
   * </pre>
   *
   * <code>string control_tower = 3;</code>
   */
  public com.google.protobuf.ByteString
      getControlTowerBytes() {
    java.lang.Object ref = controlTower_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      controlTower_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < departurePlane_.size(); i++) {
      output.writeMessage(1, departurePlane_.get(i));
    }
    for (int i = 0; i < arrivalPlane_.size(); i++) {
      output.writeMessage(2, arrivalPlane_.get(i));
    }
    if (!getControlTowerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, controlTower_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < departurePlane_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, departurePlane_.get(i));
    }
    for (int i = 0; i < arrivalPlane_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, arrivalPlane_.get(i));
    }
    if (!getControlTowerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, controlTower_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof avion.proto.InfoResponse)) {
      return super.equals(obj);
    }
    avion.proto.InfoResponse other = (avion.proto.InfoResponse) obj;

    boolean result = true;
    result = result && getDeparturePlaneList()
        .equals(other.getDeparturePlaneList());
    result = result && getArrivalPlaneList()
        .equals(other.getArrivalPlaneList());
    result = result && getControlTower()
        .equals(other.getControlTower());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDeparturePlaneCount() > 0) {
      hash = (37 * hash) + DEPARTUREPLANE_FIELD_NUMBER;
      hash = (53 * hash) + getDeparturePlaneList().hashCode();
    }
    if (getArrivalPlaneCount() > 0) {
      hash = (37 * hash) + ARRIVALPLANE_FIELD_NUMBER;
      hash = (53 * hash) + getArrivalPlaneList().hashCode();
    }
    hash = (37 * hash) + CONTROL_TOWER_FIELD_NUMBER;
    hash = (53 * hash) + getControlTower().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static avion.proto.InfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.InfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.InfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.InfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.InfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.InfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.InfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.InfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.InfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static avion.proto.InfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.InfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.InfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(avion.proto.InfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tareados.InfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tareados.InfoResponse)
      avion.proto.InfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_InfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_InfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avion.proto.InfoResponse.class, avion.proto.InfoResponse.Builder.class);
    }

    // Construct using avion.proto.InfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDeparturePlaneFieldBuilder();
        getArrivalPlaneFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (departurePlaneBuilder_ == null) {
        departurePlane_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        departurePlaneBuilder_.clear();
      }
      if (arrivalPlaneBuilder_ == null) {
        arrivalPlane_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        arrivalPlaneBuilder_.clear();
      }
      controlTower_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_InfoResponse_descriptor;
    }

    public avion.proto.InfoResponse getDefaultInstanceForType() {
      return avion.proto.InfoResponse.getDefaultInstance();
    }

    public avion.proto.InfoResponse build() {
      avion.proto.InfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public avion.proto.InfoResponse buildPartial() {
      avion.proto.InfoResponse result = new avion.proto.InfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (departurePlaneBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          departurePlane_ = java.util.Collections.unmodifiableList(departurePlane_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.departurePlane_ = departurePlane_;
      } else {
        result.departurePlane_ = departurePlaneBuilder_.build();
      }
      if (arrivalPlaneBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          arrivalPlane_ = java.util.Collections.unmodifiableList(arrivalPlane_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.arrivalPlane_ = arrivalPlane_;
      } else {
        result.arrivalPlane_ = arrivalPlaneBuilder_.build();
      }
      result.controlTower_ = controlTower_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof avion.proto.InfoResponse) {
        return mergeFrom((avion.proto.InfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(avion.proto.InfoResponse other) {
      if (other == avion.proto.InfoResponse.getDefaultInstance()) return this;
      if (departurePlaneBuilder_ == null) {
        if (!other.departurePlane_.isEmpty()) {
          if (departurePlane_.isEmpty()) {
            departurePlane_ = other.departurePlane_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDeparturePlaneIsMutable();
            departurePlane_.addAll(other.departurePlane_);
          }
          onChanged();
        }
      } else {
        if (!other.departurePlane_.isEmpty()) {
          if (departurePlaneBuilder_.isEmpty()) {
            departurePlaneBuilder_.dispose();
            departurePlaneBuilder_ = null;
            departurePlane_ = other.departurePlane_;
            bitField0_ = (bitField0_ & ~0x00000001);
            departurePlaneBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDeparturePlaneFieldBuilder() : null;
          } else {
            departurePlaneBuilder_.addAllMessages(other.departurePlane_);
          }
        }
      }
      if (arrivalPlaneBuilder_ == null) {
        if (!other.arrivalPlane_.isEmpty()) {
          if (arrivalPlane_.isEmpty()) {
            arrivalPlane_ = other.arrivalPlane_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArrivalPlaneIsMutable();
            arrivalPlane_.addAll(other.arrivalPlane_);
          }
          onChanged();
        }
      } else {
        if (!other.arrivalPlane_.isEmpty()) {
          if (arrivalPlaneBuilder_.isEmpty()) {
            arrivalPlaneBuilder_.dispose();
            arrivalPlaneBuilder_ = null;
            arrivalPlane_ = other.arrivalPlane_;
            bitField0_ = (bitField0_ & ~0x00000002);
            arrivalPlaneBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArrivalPlaneFieldBuilder() : null;
          } else {
            arrivalPlaneBuilder_.addAllMessages(other.arrivalPlane_);
          }
        }
      }
      if (!other.getControlTower().isEmpty()) {
        controlTower_ = other.controlTower_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      avion.proto.InfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (avion.proto.InfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<avion.proto.PlaneMsge> departurePlane_ =
      java.util.Collections.emptyList();
    private void ensureDeparturePlaneIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        departurePlane_ = new java.util.ArrayList<avion.proto.PlaneMsge>(departurePlane_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> departurePlaneBuilder_;

    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public java.util.List<avion.proto.PlaneMsge> getDeparturePlaneList() {
      if (departurePlaneBuilder_ == null) {
        return java.util.Collections.unmodifiableList(departurePlane_);
      } else {
        return departurePlaneBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public int getDeparturePlaneCount() {
      if (departurePlaneBuilder_ == null) {
        return departurePlane_.size();
      } else {
        return departurePlaneBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public avion.proto.PlaneMsge getDeparturePlane(int index) {
      if (departurePlaneBuilder_ == null) {
        return departurePlane_.get(index);
      } else {
        return departurePlaneBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder setDeparturePlane(
        int index, avion.proto.PlaneMsge value) {
      if (departurePlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeparturePlaneIsMutable();
        departurePlane_.set(index, value);
        onChanged();
      } else {
        departurePlaneBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder setDeparturePlane(
        int index, avion.proto.PlaneMsge.Builder builderForValue) {
      if (departurePlaneBuilder_ == null) {
        ensureDeparturePlaneIsMutable();
        departurePlane_.set(index, builderForValue.build());
        onChanged();
      } else {
        departurePlaneBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder addDeparturePlane(avion.proto.PlaneMsge value) {
      if (departurePlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeparturePlaneIsMutable();
        departurePlane_.add(value);
        onChanged();
      } else {
        departurePlaneBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder addDeparturePlane(
        int index, avion.proto.PlaneMsge value) {
      if (departurePlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDeparturePlaneIsMutable();
        departurePlane_.add(index, value);
        onChanged();
      } else {
        departurePlaneBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder addDeparturePlane(
        avion.proto.PlaneMsge.Builder builderForValue) {
      if (departurePlaneBuilder_ == null) {
        ensureDeparturePlaneIsMutable();
        departurePlane_.add(builderForValue.build());
        onChanged();
      } else {
        departurePlaneBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder addDeparturePlane(
        int index, avion.proto.PlaneMsge.Builder builderForValue) {
      if (departurePlaneBuilder_ == null) {
        ensureDeparturePlaneIsMutable();
        departurePlane_.add(index, builderForValue.build());
        onChanged();
      } else {
        departurePlaneBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder addAllDeparturePlane(
        java.lang.Iterable<? extends avion.proto.PlaneMsge> values) {
      if (departurePlaneBuilder_ == null) {
        ensureDeparturePlaneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, departurePlane_);
        onChanged();
      } else {
        departurePlaneBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder clearDeparturePlane() {
      if (departurePlaneBuilder_ == null) {
        departurePlane_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        departurePlaneBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public Builder removeDeparturePlane(int index) {
      if (departurePlaneBuilder_ == null) {
        ensureDeparturePlaneIsMutable();
        departurePlane_.remove(index);
        onChanged();
      } else {
        departurePlaneBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public avion.proto.PlaneMsge.Builder getDeparturePlaneBuilder(
        int index) {
      return getDeparturePlaneFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public avion.proto.PlaneMsgeOrBuilder getDeparturePlaneOrBuilder(
        int index) {
      if (departurePlaneBuilder_ == null) {
        return departurePlane_.get(index);  } else {
        return departurePlaneBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public java.util.List<? extends avion.proto.PlaneMsgeOrBuilder> 
         getDeparturePlaneOrBuilderList() {
      if (departurePlaneBuilder_ != null) {
        return departurePlaneBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(departurePlane_);
      }
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public avion.proto.PlaneMsge.Builder addDeparturePlaneBuilder() {
      return getDeparturePlaneFieldBuilder().addBuilder(
          avion.proto.PlaneMsge.getDefaultInstance());
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public avion.proto.PlaneMsge.Builder addDeparturePlaneBuilder(
        int index) {
      return getDeparturePlaneFieldBuilder().addBuilder(
          index, avion.proto.PlaneMsge.getDefaultInstance());
    }
    /**
     * <pre>
     *id de vuelo de salida desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge departurePlane = 1;</code>
     */
    public java.util.List<avion.proto.PlaneMsge.Builder> 
         getDeparturePlaneBuilderList() {
      return getDeparturePlaneFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> 
        getDeparturePlaneFieldBuilder() {
      if (departurePlaneBuilder_ == null) {
        departurePlaneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder>(
                departurePlane_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        departurePlane_ = null;
      }
      return departurePlaneBuilder_;
    }

    private java.util.List<avion.proto.PlaneMsge> arrivalPlane_ =
      java.util.Collections.emptyList();
    private void ensureArrivalPlaneIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        arrivalPlane_ = new java.util.ArrayList<avion.proto.PlaneMsge>(arrivalPlane_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> arrivalPlaneBuilder_;

    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public java.util.List<avion.proto.PlaneMsge> getArrivalPlaneList() {
      if (arrivalPlaneBuilder_ == null) {
        return java.util.Collections.unmodifiableList(arrivalPlane_);
      } else {
        return arrivalPlaneBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public int getArrivalPlaneCount() {
      if (arrivalPlaneBuilder_ == null) {
        return arrivalPlane_.size();
      } else {
        return arrivalPlaneBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public avion.proto.PlaneMsge getArrivalPlane(int index) {
      if (arrivalPlaneBuilder_ == null) {
        return arrivalPlane_.get(index);
      } else {
        return arrivalPlaneBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder setArrivalPlane(
        int index, avion.proto.PlaneMsge value) {
      if (arrivalPlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.set(index, value);
        onChanged();
      } else {
        arrivalPlaneBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder setArrivalPlane(
        int index, avion.proto.PlaneMsge.Builder builderForValue) {
      if (arrivalPlaneBuilder_ == null) {
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.set(index, builderForValue.build());
        onChanged();
      } else {
        arrivalPlaneBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder addArrivalPlane(avion.proto.PlaneMsge value) {
      if (arrivalPlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.add(value);
        onChanged();
      } else {
        arrivalPlaneBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder addArrivalPlane(
        int index, avion.proto.PlaneMsge value) {
      if (arrivalPlaneBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.add(index, value);
        onChanged();
      } else {
        arrivalPlaneBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder addArrivalPlane(
        avion.proto.PlaneMsge.Builder builderForValue) {
      if (arrivalPlaneBuilder_ == null) {
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.add(builderForValue.build());
        onChanged();
      } else {
        arrivalPlaneBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder addArrivalPlane(
        int index, avion.proto.PlaneMsge.Builder builderForValue) {
      if (arrivalPlaneBuilder_ == null) {
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.add(index, builderForValue.build());
        onChanged();
      } else {
        arrivalPlaneBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder addAllArrivalPlane(
        java.lang.Iterable<? extends avion.proto.PlaneMsge> values) {
      if (arrivalPlaneBuilder_ == null) {
        ensureArrivalPlaneIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arrivalPlane_);
        onChanged();
      } else {
        arrivalPlaneBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder clearArrivalPlane() {
      if (arrivalPlaneBuilder_ == null) {
        arrivalPlane_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        arrivalPlaneBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public Builder removeArrivalPlane(int index) {
      if (arrivalPlaneBuilder_ == null) {
        ensureArrivalPlaneIsMutable();
        arrivalPlane_.remove(index);
        onChanged();
      } else {
        arrivalPlaneBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public avion.proto.PlaneMsge.Builder getArrivalPlaneBuilder(
        int index) {
      return getArrivalPlaneFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public avion.proto.PlaneMsgeOrBuilder getArrivalPlaneOrBuilder(
        int index) {
      if (arrivalPlaneBuilder_ == null) {
        return arrivalPlane_.get(index);  } else {
        return arrivalPlaneBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public java.util.List<? extends avion.proto.PlaneMsgeOrBuilder> 
         getArrivalPlaneOrBuilderList() {
      if (arrivalPlaneBuilder_ != null) {
        return arrivalPlaneBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(arrivalPlane_);
      }
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public avion.proto.PlaneMsge.Builder addArrivalPlaneBuilder() {
      return getArrivalPlaneFieldBuilder().addBuilder(
          avion.proto.PlaneMsge.getDefaultInstance());
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public avion.proto.PlaneMsge.Builder addArrivalPlaneBuilder(
        int index) {
      return getArrivalPlaneFieldBuilder().addBuilder(
          index, avion.proto.PlaneMsge.getDefaultInstance());
    }
    /**
     * <pre>
     *id de vuelo de entrada desde el aeropuerto
     * </pre>
     *
     * <code>repeated .tareados.PlaneMsge arrivalPlane = 2;</code>
     */
    public java.util.List<avion.proto.PlaneMsge.Builder> 
         getArrivalPlaneBuilderList() {
      return getArrivalPlaneFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> 
        getArrivalPlaneFieldBuilder() {
      if (arrivalPlaneBuilder_ == null) {
        arrivalPlaneBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder>(
                arrivalPlane_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        arrivalPlane_ = null;
      }
      return arrivalPlaneBuilder_;
    }

    private java.lang.Object controlTower_ = "";
    /**
     * <pre>
     *nombre de la torre de control
     * </pre>
     *
     * <code>string control_tower = 3;</code>
     */
    public java.lang.String getControlTower() {
      java.lang.Object ref = controlTower_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        controlTower_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *nombre de la torre de control
     * </pre>
     *
     * <code>string control_tower = 3;</code>
     */
    public com.google.protobuf.ByteString
        getControlTowerBytes() {
      java.lang.Object ref = controlTower_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        controlTower_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *nombre de la torre de control
     * </pre>
     *
     * <code>string control_tower = 3;</code>
     */
    public Builder setControlTower(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      controlTower_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *nombre de la torre de control
     * </pre>
     *
     * <code>string control_tower = 3;</code>
     */
    public Builder clearControlTower() {
      
      controlTower_ = getDefaultInstance().getControlTower();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *nombre de la torre de control
     * </pre>
     *
     * <code>string control_tower = 3;</code>
     */
    public Builder setControlTowerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      controlTower_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tareados.InfoResponse)
  }

  // @@protoc_insertion_point(class_scope:tareados.InfoResponse)
  private static final avion.proto.InfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new avion.proto.InfoResponse();
  }

  public static avion.proto.InfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<InfoResponse>() {
    public InfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InfoResponse> getParserForType() {
    return PARSER;
  }

  public avion.proto.InfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

