// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

public interface LandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.LandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dest = 1;</code>
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 1;</code>
   */
  com.google.protobuf.ByteString
      getDestBytes();

  /**
   * <code>.tareados.PlaneMsge plane = 2;</code>
   */
  boolean hasPlane();
  /**
   * <code>.tareados.PlaneMsge plane = 2;</code>
   */
  avion.proto.PlaneMsge getPlane();
  /**
   * <code>.tareados.PlaneMsge plane = 2;</code>
   */
  avion.proto.PlaneMsgeOrBuilder getPlaneOrBuilder();
}
