// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

/**
 * Protobuf type {@code tareados.TakeoffResponse}
 */
public  final class TakeoffResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tareados.TakeoffResponse)
    TakeoffResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TakeoffResponse.newBuilder() to construct.
  private TakeoffResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TakeoffResponse() {
    altitude_ = 0;
    runway_ = 0;
    dest_ = "";
    queuePos_ = 0;
    prevPlane_ = "";
    destOK_ = false;
    restrOK_ = false;
    instOK_ = false;
    destName_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TakeoffResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            altitude_ = input.readInt32();
            break;
          }
          case 16: {

            runway_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dest_ = s;
            break;
          }
          case 32: {

            queuePos_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            prevPlane_ = s;
            break;
          }
          case 48: {

            destOK_ = input.readBool();
            break;
          }
          case 56: {

            restrOK_ = input.readBool();
            break;
          }
          case 64: {

            instOK_ = input.readBool();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            destName_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            avion.proto.TakeoffResponse.class, avion.proto.TakeoffResponse.Builder.class);
  }

  public static final int ALTITUDE_FIELD_NUMBER = 1;
  private int altitude_;
  /**
   * <code>int32 altitude = 1;</code>
   */
  public int getAltitude() {
    return altitude_;
  }

  public static final int RUNWAY_FIELD_NUMBER = 2;
  private int runway_;
  /**
   * <code>int32 runway = 2;</code>
   */
  public int getRunway() {
    return runway_;
  }

  public static final int DEST_FIELD_NUMBER = 3;
  private volatile java.lang.Object dest_;
  /**
   * <code>string dest = 3;</code>
   */
  public java.lang.String getDest() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dest_ = s;
      return s;
    }
  }
  /**
   * <code>string dest = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDestBytes() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUEUEPOS_FIELD_NUMBER = 4;
  private int queuePos_;
  /**
   * <code>int32 queuePos = 4;</code>
   */
  public int getQueuePos() {
    return queuePos_;
  }

  public static final int PREVPLANE_FIELD_NUMBER = 5;
  private volatile java.lang.Object prevPlane_;
  /**
   * <code>string prevPlane = 5;</code>
   */
  public java.lang.String getPrevPlane() {
    java.lang.Object ref = prevPlane_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prevPlane_ = s;
      return s;
    }
  }
  /**
   * <code>string prevPlane = 5;</code>
   */
  public com.google.protobuf.ByteString
      getPrevPlaneBytes() {
    java.lang.Object ref = prevPlane_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prevPlane_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTOK_FIELD_NUMBER = 6;
  private boolean destOK_;
  /**
   * <pre>
   *si el destino es valido destOK = true sino no
   * </pre>
   *
   * <code>bool destOK = 6;</code>
   */
  public boolean getDestOK() {
    return destOK_;
  }

  public static final int RESTROK_FIELD_NUMBER = 7;
  private boolean restrOK_;
  /**
   * <pre>
   *si la restricciones se cumplen restrOK = true sino no
   * </pre>
   *
   * <code>bool restrOK = 7;</code>
   */
  public boolean getRestrOK() {
    return restrOK_;
  }

  public static final int INSTOK_FIELD_NUMBER = 8;
  private boolean instOK_;
  /**
   * <pre>
   *si el avión envio instrucciones = true sino no
   * </pre>
   *
   * <code>bool instOK = 8;</code>
   */
  public boolean getInstOK() {
    return instOK_;
  }

  public static final int DESTNAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object destName_;
  /**
   * <code>string destName = 9;</code>
   */
  public java.lang.String getDestName() {
    java.lang.Object ref = destName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destName_ = s;
      return s;
    }
  }
  /**
   * <code>string destName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDestNameBytes() {
    java.lang.Object ref = destName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      destName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (altitude_ != 0) {
      output.writeInt32(1, altitude_);
    }
    if (runway_ != 0) {
      output.writeInt32(2, runway_);
    }
    if (!getDestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dest_);
    }
    if (queuePos_ != 0) {
      output.writeInt32(4, queuePos_);
    }
    if (!getPrevPlaneBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, prevPlane_);
    }
    if (destOK_ != false) {
      output.writeBool(6, destOK_);
    }
    if (restrOK_ != false) {
      output.writeBool(7, restrOK_);
    }
    if (instOK_ != false) {
      output.writeBool(8, instOK_);
    }
    if (!getDestNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, destName_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (altitude_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, altitude_);
    }
    if (runway_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, runway_);
    }
    if (!getDestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dest_);
    }
    if (queuePos_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, queuePos_);
    }
    if (!getPrevPlaneBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, prevPlane_);
    }
    if (destOK_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, destOK_);
    }
    if (restrOK_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, restrOK_);
    }
    if (instOK_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, instOK_);
    }
    if (!getDestNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, destName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof avion.proto.TakeoffResponse)) {
      return super.equals(obj);
    }
    avion.proto.TakeoffResponse other = (avion.proto.TakeoffResponse) obj;

    boolean result = true;
    result = result && (getAltitude()
        == other.getAltitude());
    result = result && (getRunway()
        == other.getRunway());
    result = result && getDest()
        .equals(other.getDest());
    result = result && (getQueuePos()
        == other.getQueuePos());
    result = result && getPrevPlane()
        .equals(other.getPrevPlane());
    result = result && (getDestOK()
        == other.getDestOK());
    result = result && (getRestrOK()
        == other.getRestrOK());
    result = result && (getInstOK()
        == other.getInstOK());
    result = result && getDestName()
        .equals(other.getDestName());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getAltitude();
    hash = (37 * hash) + RUNWAY_FIELD_NUMBER;
    hash = (53 * hash) + getRunway();
    hash = (37 * hash) + DEST_FIELD_NUMBER;
    hash = (53 * hash) + getDest().hashCode();
    hash = (37 * hash) + QUEUEPOS_FIELD_NUMBER;
    hash = (53 * hash) + getQueuePos();
    hash = (37 * hash) + PREVPLANE_FIELD_NUMBER;
    hash = (53 * hash) + getPrevPlane().hashCode();
    hash = (37 * hash) + DESTOK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDestOK());
    hash = (37 * hash) + RESTROK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRestrOK());
    hash = (37 * hash) + INSTOK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInstOK());
    hash = (37 * hash) + DESTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDestName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static avion.proto.TakeoffResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.TakeoffResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(avion.proto.TakeoffResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tareados.TakeoffResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tareados.TakeoffResponse)
      avion.proto.TakeoffResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avion.proto.TakeoffResponse.class, avion.proto.TakeoffResponse.Builder.class);
    }

    // Construct using avion.proto.TakeoffResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      altitude_ = 0;

      runway_ = 0;

      dest_ = "";

      queuePos_ = 0;

      prevPlane_ = "";

      destOK_ = false;

      restrOK_ = false;

      instOK_ = false;

      destName_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffResponse_descriptor;
    }

    public avion.proto.TakeoffResponse getDefaultInstanceForType() {
      return avion.proto.TakeoffResponse.getDefaultInstance();
    }

    public avion.proto.TakeoffResponse build() {
      avion.proto.TakeoffResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public avion.proto.TakeoffResponse buildPartial() {
      avion.proto.TakeoffResponse result = new avion.proto.TakeoffResponse(this);
      result.altitude_ = altitude_;
      result.runway_ = runway_;
      result.dest_ = dest_;
      result.queuePos_ = queuePos_;
      result.prevPlane_ = prevPlane_;
      result.destOK_ = destOK_;
      result.restrOK_ = restrOK_;
      result.instOK_ = instOK_;
      result.destName_ = destName_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof avion.proto.TakeoffResponse) {
        return mergeFrom((avion.proto.TakeoffResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(avion.proto.TakeoffResponse other) {
      if (other == avion.proto.TakeoffResponse.getDefaultInstance()) return this;
      if (other.getAltitude() != 0) {
        setAltitude(other.getAltitude());
      }
      if (other.getRunway() != 0) {
        setRunway(other.getRunway());
      }
      if (!other.getDest().isEmpty()) {
        dest_ = other.dest_;
        onChanged();
      }
      if (other.getQueuePos() != 0) {
        setQueuePos(other.getQueuePos());
      }
      if (!other.getPrevPlane().isEmpty()) {
        prevPlane_ = other.prevPlane_;
        onChanged();
      }
      if (other.getDestOK() != false) {
        setDestOK(other.getDestOK());
      }
      if (other.getRestrOK() != false) {
        setRestrOK(other.getRestrOK());
      }
      if (other.getInstOK() != false) {
        setInstOK(other.getInstOK());
      }
      if (!other.getDestName().isEmpty()) {
        destName_ = other.destName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      avion.proto.TakeoffResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (avion.proto.TakeoffResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int altitude_ ;
    /**
     * <code>int32 altitude = 1;</code>
     */
    public int getAltitude() {
      return altitude_;
    }
    /**
     * <code>int32 altitude = 1;</code>
     */
    public Builder setAltitude(int value) {
      
      altitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 altitude = 1;</code>
     */
    public Builder clearAltitude() {
      
      altitude_ = 0;
      onChanged();
      return this;
    }

    private int runway_ ;
    /**
     * <code>int32 runway = 2;</code>
     */
    public int getRunway() {
      return runway_;
    }
    /**
     * <code>int32 runway = 2;</code>
     */
    public Builder setRunway(int value) {
      
      runway_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 runway = 2;</code>
     */
    public Builder clearRunway() {
      
      runway_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object dest_ = "";
    /**
     * <code>string dest = 3;</code>
     */
    public java.lang.String getDest() {
      java.lang.Object ref = dest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dest = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDestBytes() {
      java.lang.Object ref = dest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dest = 3;</code>
     */
    public Builder setDest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 3;</code>
     */
    public Builder clearDest() {
      
      dest_ = getDefaultInstance().getDest();
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 3;</code>
     */
    public Builder setDestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dest_ = value;
      onChanged();
      return this;
    }

    private int queuePos_ ;
    /**
     * <code>int32 queuePos = 4;</code>
     */
    public int getQueuePos() {
      return queuePos_;
    }
    /**
     * <code>int32 queuePos = 4;</code>
     */
    public Builder setQueuePos(int value) {
      
      queuePos_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 queuePos = 4;</code>
     */
    public Builder clearQueuePos() {
      
      queuePos_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object prevPlane_ = "";
    /**
     * <code>string prevPlane = 5;</code>
     */
    public java.lang.String getPrevPlane() {
      java.lang.Object ref = prevPlane_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prevPlane_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prevPlane = 5;</code>
     */
    public com.google.protobuf.ByteString
        getPrevPlaneBytes() {
      java.lang.Object ref = prevPlane_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prevPlane_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prevPlane = 5;</code>
     */
    public Builder setPrevPlane(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prevPlane_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prevPlane = 5;</code>
     */
    public Builder clearPrevPlane() {
      
      prevPlane_ = getDefaultInstance().getPrevPlane();
      onChanged();
      return this;
    }
    /**
     * <code>string prevPlane = 5;</code>
     */
    public Builder setPrevPlaneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prevPlane_ = value;
      onChanged();
      return this;
    }

    private boolean destOK_ ;
    /**
     * <pre>
     *si el destino es valido destOK = true sino no
     * </pre>
     *
     * <code>bool destOK = 6;</code>
     */
    public boolean getDestOK() {
      return destOK_;
    }
    /**
     * <pre>
     *si el destino es valido destOK = true sino no
     * </pre>
     *
     * <code>bool destOK = 6;</code>
     */
    public Builder setDestOK(boolean value) {
      
      destOK_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *si el destino es valido destOK = true sino no
     * </pre>
     *
     * <code>bool destOK = 6;</code>
     */
    public Builder clearDestOK() {
      
      destOK_ = false;
      onChanged();
      return this;
    }

    private boolean restrOK_ ;
    /**
     * <pre>
     *si la restricciones se cumplen restrOK = true sino no
     * </pre>
     *
     * <code>bool restrOK = 7;</code>
     */
    public boolean getRestrOK() {
      return restrOK_;
    }
    /**
     * <pre>
     *si la restricciones se cumplen restrOK = true sino no
     * </pre>
     *
     * <code>bool restrOK = 7;</code>
     */
    public Builder setRestrOK(boolean value) {
      
      restrOK_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *si la restricciones se cumplen restrOK = true sino no
     * </pre>
     *
     * <code>bool restrOK = 7;</code>
     */
    public Builder clearRestrOK() {
      
      restrOK_ = false;
      onChanged();
      return this;
    }

    private boolean instOK_ ;
    /**
     * <pre>
     *si el avión envio instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 8;</code>
     */
    public boolean getInstOK() {
      return instOK_;
    }
    /**
     * <pre>
     *si el avión envio instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 8;</code>
     */
    public Builder setInstOK(boolean value) {
      
      instOK_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *si el avión envio instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 8;</code>
     */
    public Builder clearInstOK() {
      
      instOK_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object destName_ = "";
    /**
     * <code>string destName = 9;</code>
     */
    public java.lang.String getDestName() {
      java.lang.Object ref = destName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string destName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDestNameBytes() {
      java.lang.Object ref = destName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destName = 9;</code>
     */
    public Builder setDestName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      destName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string destName = 9;</code>
     */
    public Builder clearDestName() {
      
      destName_ = getDefaultInstance().getDestName();
      onChanged();
      return this;
    }
    /**
     * <code>string destName = 9;</code>
     */
    public Builder setDestNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      destName_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tareados.TakeoffResponse)
  }

  // @@protoc_insertion_point(class_scope:tareados.TakeoffResponse)
  private static final avion.proto.TakeoffResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new avion.proto.TakeoffResponse();
  }

  public static avion.proto.TakeoffResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TakeoffResponse>
      PARSER = new com.google.protobuf.AbstractParser<TakeoffResponse>() {
    public TakeoffResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TakeoffResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TakeoffResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TakeoffResponse> getParserForType() {
    return PARSER;
  }

  public avion.proto.TakeoffResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

