// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planecontrol.proto

package avion.proto;

/**
 * Protobuf type {@code tareados.TakeoffRequest}
 */
public  final class TakeoffRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tareados.TakeoffRequest)
    TakeoffRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TakeoffRequest.newBuilder() to construct.
  private TakeoffRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TakeoffRequest() {
    dest_ = "";
    instOK_ = false;
    flyOK_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TakeoffRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            avion.proto.PlaneMsge.Builder subBuilder = null;
            if (plane_ != null) {
              subBuilder = plane_.toBuilder();
            }
            plane_ = input.readMessage(avion.proto.PlaneMsge.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(plane_);
              plane_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dest_ = s;
            break;
          }
          case 24: {

            instOK_ = input.readBool();
            break;
          }
          case 32: {

            flyOK_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            avion.proto.TakeoffRequest.class, avion.proto.TakeoffRequest.Builder.class);
  }

  public static final int PLANE_FIELD_NUMBER = 1;
  private avion.proto.PlaneMsge plane_;
  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  public boolean hasPlane() {
    return plane_ != null;
  }
  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  public avion.proto.PlaneMsge getPlane() {
    return plane_ == null ? avion.proto.PlaneMsge.getDefaultInstance() : plane_;
  }
  /**
   * <code>.tareados.PlaneMsge plane = 1;</code>
   */
  public avion.proto.PlaneMsgeOrBuilder getPlaneOrBuilder() {
    return getPlane();
  }

  public static final int DEST_FIELD_NUMBER = 2;
  private volatile java.lang.Object dest_;
  /**
   * <code>string dest = 2;</code>
   */
  public java.lang.String getDest() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dest_ = s;
      return s;
    }
  }
  /**
   * <code>string dest = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDestBytes() {
    java.lang.Object ref = dest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTOK_FIELD_NUMBER = 3;
  private boolean instOK_;
  /**
   * <pre>
   *si el avión necesita instrucciones = true sino no
   * </pre>
   *
   * <code>bool instOK = 3;</code>
   */
  public boolean getInstOK() {
    return instOK_;
  }

  public static final int FLYOK_FIELD_NUMBER = 4;
  private boolean flyOK_;
  /**
   * <pre>
   *si el avion esta listo para despegar (presionar enter)
   * </pre>
   *
   * <code>bool flyOK = 4;</code>
   */
  public boolean getFlyOK() {
    return flyOK_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (plane_ != null) {
      output.writeMessage(1, getPlane());
    }
    if (!getDestBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dest_);
    }
    if (instOK_ != false) {
      output.writeBool(3, instOK_);
    }
    if (flyOK_ != false) {
      output.writeBool(4, flyOK_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (plane_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPlane());
    }
    if (!getDestBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dest_);
    }
    if (instOK_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, instOK_);
    }
    if (flyOK_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, flyOK_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof avion.proto.TakeoffRequest)) {
      return super.equals(obj);
    }
    avion.proto.TakeoffRequest other = (avion.proto.TakeoffRequest) obj;

    boolean result = true;
    result = result && (hasPlane() == other.hasPlane());
    if (hasPlane()) {
      result = result && getPlane()
          .equals(other.getPlane());
    }
    result = result && getDest()
        .equals(other.getDest());
    result = result && (getInstOK()
        == other.getInstOK());
    result = result && (getFlyOK()
        == other.getFlyOK());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPlane()) {
      hash = (37 * hash) + PLANE_FIELD_NUMBER;
      hash = (53 * hash) + getPlane().hashCode();
    }
    hash = (37 * hash) + DEST_FIELD_NUMBER;
    hash = (53 * hash) + getDest().hashCode();
    hash = (37 * hash) + INSTOK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInstOK());
    hash = (37 * hash) + FLYOK_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFlyOK());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static avion.proto.TakeoffRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.proto.TakeoffRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.TakeoffRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.proto.TakeoffRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(avion.proto.TakeoffRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tareados.TakeoffRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tareados.TakeoffRequest)
      avion.proto.TakeoffRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avion.proto.TakeoffRequest.class, avion.proto.TakeoffRequest.Builder.class);
    }

    // Construct using avion.proto.TakeoffRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (planeBuilder_ == null) {
        plane_ = null;
      } else {
        plane_ = null;
        planeBuilder_ = null;
      }
      dest_ = "";

      instOK_ = false;

      flyOK_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return avion.proto.PlaneControlProtos.internal_static_tareados_TakeoffRequest_descriptor;
    }

    public avion.proto.TakeoffRequest getDefaultInstanceForType() {
      return avion.proto.TakeoffRequest.getDefaultInstance();
    }

    public avion.proto.TakeoffRequest build() {
      avion.proto.TakeoffRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public avion.proto.TakeoffRequest buildPartial() {
      avion.proto.TakeoffRequest result = new avion.proto.TakeoffRequest(this);
      if (planeBuilder_ == null) {
        result.plane_ = plane_;
      } else {
        result.plane_ = planeBuilder_.build();
      }
      result.dest_ = dest_;
      result.instOK_ = instOK_;
      result.flyOK_ = flyOK_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof avion.proto.TakeoffRequest) {
        return mergeFrom((avion.proto.TakeoffRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(avion.proto.TakeoffRequest other) {
      if (other == avion.proto.TakeoffRequest.getDefaultInstance()) return this;
      if (other.hasPlane()) {
        mergePlane(other.getPlane());
      }
      if (!other.getDest().isEmpty()) {
        dest_ = other.dest_;
        onChanged();
      }
      if (other.getInstOK() != false) {
        setInstOK(other.getInstOK());
      }
      if (other.getFlyOK() != false) {
        setFlyOK(other.getFlyOK());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      avion.proto.TakeoffRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (avion.proto.TakeoffRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private avion.proto.PlaneMsge plane_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> planeBuilder_;
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public boolean hasPlane() {
      return planeBuilder_ != null || plane_ != null;
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public avion.proto.PlaneMsge getPlane() {
      if (planeBuilder_ == null) {
        return plane_ == null ? avion.proto.PlaneMsge.getDefaultInstance() : plane_;
      } else {
        return planeBuilder_.getMessage();
      }
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public Builder setPlane(avion.proto.PlaneMsge value) {
      if (planeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        plane_ = value;
        onChanged();
      } else {
        planeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public Builder setPlane(
        avion.proto.PlaneMsge.Builder builderForValue) {
      if (planeBuilder_ == null) {
        plane_ = builderForValue.build();
        onChanged();
      } else {
        planeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public Builder mergePlane(avion.proto.PlaneMsge value) {
      if (planeBuilder_ == null) {
        if (plane_ != null) {
          plane_ =
            avion.proto.PlaneMsge.newBuilder(plane_).mergeFrom(value).buildPartial();
        } else {
          plane_ = value;
        }
        onChanged();
      } else {
        planeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public Builder clearPlane() {
      if (planeBuilder_ == null) {
        plane_ = null;
        onChanged();
      } else {
        plane_ = null;
        planeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public avion.proto.PlaneMsge.Builder getPlaneBuilder() {
      
      onChanged();
      return getPlaneFieldBuilder().getBuilder();
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    public avion.proto.PlaneMsgeOrBuilder getPlaneOrBuilder() {
      if (planeBuilder_ != null) {
        return planeBuilder_.getMessageOrBuilder();
      } else {
        return plane_ == null ?
            avion.proto.PlaneMsge.getDefaultInstance() : plane_;
      }
    }
    /**
     * <code>.tareados.PlaneMsge plane = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder> 
        getPlaneFieldBuilder() {
      if (planeBuilder_ == null) {
        planeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            avion.proto.PlaneMsge, avion.proto.PlaneMsge.Builder, avion.proto.PlaneMsgeOrBuilder>(
                getPlane(),
                getParentForChildren(),
                isClean());
        plane_ = null;
      }
      return planeBuilder_;
    }

    private java.lang.Object dest_ = "";
    /**
     * <code>string dest = 2;</code>
     */
    public java.lang.String getDest() {
      java.lang.Object ref = dest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDestBytes() {
      java.lang.Object ref = dest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dest = 2;</code>
     */
    public Builder setDest(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dest_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 2;</code>
     */
    public Builder clearDest() {
      
      dest_ = getDefaultInstance().getDest();
      onChanged();
      return this;
    }
    /**
     * <code>string dest = 2;</code>
     */
    public Builder setDestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dest_ = value;
      onChanged();
      return this;
    }

    private boolean instOK_ ;
    /**
     * <pre>
     *si el avión necesita instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 3;</code>
     */
    public boolean getInstOK() {
      return instOK_;
    }
    /**
     * <pre>
     *si el avión necesita instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 3;</code>
     */
    public Builder setInstOK(boolean value) {
      
      instOK_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *si el avión necesita instrucciones = true sino no
     * </pre>
     *
     * <code>bool instOK = 3;</code>
     */
    public Builder clearInstOK() {
      
      instOK_ = false;
      onChanged();
      return this;
    }

    private boolean flyOK_ ;
    /**
     * <pre>
     *si el avion esta listo para despegar (presionar enter)
     * </pre>
     *
     * <code>bool flyOK = 4;</code>
     */
    public boolean getFlyOK() {
      return flyOK_;
    }
    /**
     * <pre>
     *si el avion esta listo para despegar (presionar enter)
     * </pre>
     *
     * <code>bool flyOK = 4;</code>
     */
    public Builder setFlyOK(boolean value) {
      
      flyOK_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *si el avion esta listo para despegar (presionar enter)
     * </pre>
     *
     * <code>bool flyOK = 4;</code>
     */
    public Builder clearFlyOK() {
      
      flyOK_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tareados.TakeoffRequest)
  }

  // @@protoc_insertion_point(class_scope:tareados.TakeoffRequest)
  private static final avion.proto.TakeoffRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new avion.proto.TakeoffRequest();
  }

  public static avion.proto.TakeoffRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TakeoffRequest>
      PARSER = new com.google.protobuf.AbstractParser<TakeoffRequest>() {
    public TakeoffRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TakeoffRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TakeoffRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TakeoffRequest> getParserForType() {
    return PARSER;
  }

  public avion.proto.TakeoffRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

