// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/planecontrol.proto

package avion;

/**
 * Protobuf type {@code tareados.LandResponse}
 */
public  final class LandResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tareados.LandResponse)
    LandResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LandResponse.newBuilder() to construct.
  private LandResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LandResponse() {
    runway_ = 0;
    queue_ = 0;
    altitude_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LandResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            runway_ = input.readInt32();
            break;
          }
          case 16: {

            queue_ = input.readInt32();
            break;
          }
          case 24: {

            altitude_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return avion.PlaneControl.internal_static_tareados_LandResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return avion.PlaneControl.internal_static_tareados_LandResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            avion.LandResponse.class, avion.LandResponse.Builder.class);
  }

  public static final int RUNWAY_FIELD_NUMBER = 1;
  private int runway_;
  /**
   * <code>int32 runway = 1;</code>
   */
  public int getRunway() {
    return runway_;
  }

  public static final int QUEUE_FIELD_NUMBER = 2;
  private int queue_;
  /**
   * <code>int32 queue = 2;</code>
   */
  public int getQueue() {
    return queue_;
  }

  public static final int ALTITUDE_FIELD_NUMBER = 3;
  private int altitude_;
  /**
   * <code>int32 altitude = 3;</code>
   */
  public int getAltitude() {
    return altitude_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (runway_ != 0) {
      output.writeInt32(1, runway_);
    }
    if (queue_ != 0) {
      output.writeInt32(2, queue_);
    }
    if (altitude_ != 0) {
      output.writeInt32(3, altitude_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (runway_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, runway_);
    }
    if (queue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, queue_);
    }
    if (altitude_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, altitude_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof avion.LandResponse)) {
      return super.equals(obj);
    }
    avion.LandResponse other = (avion.LandResponse) obj;

    boolean result = true;
    result = result && (getRunway()
        == other.getRunway());
    result = result && (getQueue()
        == other.getQueue());
    result = result && (getAltitude()
        == other.getAltitude());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RUNWAY_FIELD_NUMBER;
    hash = (53 * hash) + getRunway();
    hash = (37 * hash) + QUEUE_FIELD_NUMBER;
    hash = (53 * hash) + getQueue();
    hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getAltitude();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static avion.LandResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.LandResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.LandResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.LandResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.LandResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static avion.LandResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static avion.LandResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.LandResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.LandResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static avion.LandResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static avion.LandResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static avion.LandResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(avion.LandResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tareados.LandResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tareados.LandResponse)
      avion.LandResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return avion.PlaneControl.internal_static_tareados_LandResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return avion.PlaneControl.internal_static_tareados_LandResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              avion.LandResponse.class, avion.LandResponse.Builder.class);
    }

    // Construct using avion.LandResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      runway_ = 0;

      queue_ = 0;

      altitude_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return avion.PlaneControl.internal_static_tareados_LandResponse_descriptor;
    }

    @java.lang.Override
    public avion.LandResponse getDefaultInstanceForType() {
      return avion.LandResponse.getDefaultInstance();
    }

    @java.lang.Override
    public avion.LandResponse build() {
      avion.LandResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public avion.LandResponse buildPartial() {
      avion.LandResponse result = new avion.LandResponse(this);
      result.runway_ = runway_;
      result.queue_ = queue_;
      result.altitude_ = altitude_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof avion.LandResponse) {
        return mergeFrom((avion.LandResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(avion.LandResponse other) {
      if (other == avion.LandResponse.getDefaultInstance()) return this;
      if (other.getRunway() != 0) {
        setRunway(other.getRunway());
      }
      if (other.getQueue() != 0) {
        setQueue(other.getQueue());
      }
      if (other.getAltitude() != 0) {
        setAltitude(other.getAltitude());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      avion.LandResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (avion.LandResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int runway_ ;
    /**
     * <code>int32 runway = 1;</code>
     */
    public int getRunway() {
      return runway_;
    }
    /**
     * <code>int32 runway = 1;</code>
     */
    public Builder setRunway(int value) {
      
      runway_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 runway = 1;</code>
     */
    public Builder clearRunway() {
      
      runway_ = 0;
      onChanged();
      return this;
    }

    private int queue_ ;
    /**
     * <code>int32 queue = 2;</code>
     */
    public int getQueue() {
      return queue_;
    }
    /**
     * <code>int32 queue = 2;</code>
     */
    public Builder setQueue(int value) {
      
      queue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 queue = 2;</code>
     */
    public Builder clearQueue() {
      
      queue_ = 0;
      onChanged();
      return this;
    }

    private int altitude_ ;
    /**
     * <code>int32 altitude = 3;</code>
     */
    public int getAltitude() {
      return altitude_;
    }
    /**
     * <code>int32 altitude = 3;</code>
     */
    public Builder setAltitude(int value) {
      
      altitude_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 altitude = 3;</code>
     */
    public Builder clearAltitude() {
      
      altitude_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:tareados.LandResponse)
  }

  // @@protoc_insertion_point(class_scope:tareados.LandResponse)
  private static final avion.LandResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new avion.LandResponse();
  }

  public static avion.LandResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LandResponse>
      PARSER = new com.google.protobuf.AbstractParser<LandResponse>() {
    @java.lang.Override
    public LandResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LandResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LandResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LandResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public avion.LandResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

