// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/planecontrol.proto

package avion;

public interface LandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.LandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 plane_id = 1;</code>
   */
  int getPlaneId();
}
