// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/planecontrol.proto

package avion;

public interface LandResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.LandResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 runway = 1;</code>
   */
  int getRunway();

  /**
   * <code>int32 queue = 2;</code>
   */
  int getQueue();

  /**
   * <code>int32 altitude = 3;</code>
   */
  int getAltitude();
}
