// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/planecontrol.proto

package avion;

public interface planeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.plane)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 plane_id = 1;</code>
   */
  int getPlaneId();

  /**
   * <code>string source_name = 2;</code>
   */
  java.lang.String getSourceName();
  /**
   * <code>string source_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getSourceNameBytes();

  /**
   * <code>string dest_name = 3;</code>
   */
  java.lang.String getDestName();
  /**
   * <code>string dest_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getDestNameBytes();

  /**
   * <code>string departure_time = 4;</code>
   */
  java.lang.String getDepartureTime();
  /**
   * <code>string departure_time = 4;</code>
   */
  com.google.protobuf.ByteString
      getDepartureTimeBytes();

  /**
   * <code>string arrival_time = 5;</code>
   */
  java.lang.String getArrivalTime();
  /**
   * <code>string arrival_time = 5;</code>
   */
  com.google.protobuf.ByteString
      getArrivalTimeBytes();

  /**
   * <code>int32 source_runway = 6;</code>
   */
  int getSourceRunway();

  /**
   * <code>int32 dest_runway = 7;</code>
   */
  int getDestRunway();

  /**
   * <code>int32 altitude = 8;</code>
   */
  int getAltitude();
}
