// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/planecontrol.proto

package avion;

public interface TakeoffRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tareados.TakeoffRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 plane_id = 1;</code>
   */
  int getPlaneId();

  /**
   * <pre>
   *Nombre aeropuerto destino
   * </pre>
   *
   * <code>string dest_name = 2;</code>
   */
  java.lang.String getDestName();
  /**
   * <pre>
   *Nombre aeropuerto destino
   * </pre>
   *
   * <code>string dest_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getDestNameBytes();

  /**
   * <code>int32 passengers = 3;</code>
   */
  int getPassengers();

  /**
   * <code>int32 fuel = 4;</code>
   */
  int getFuel();

  /**
   * <code>int32 max_load = 5;</code>
   */
  int getMaxLoad();
}
